### ISSUE TITLE
Error al realizar pedido

### ISSUE THREAD

**Issue by Nidev-lab** [agustines82/ComiteandoRestaurant#42]
Buen@s!! como va?   encontre en el codigo este inconveniente a la hora de hacer un pedido, que si bien no es un error , deberia estar indicado para que el problema no suceda.... 

![image](https://user-images.githubusercontent.com/53904695/206603166-9ed08e58-6c84-49d1-a668-0e99cae97d2e.png)
 
Como vemos en esta primera imagen , se ingresa el pedido con direccion pero sin indicaciones .

![image](https://user-images.githubusercontent.com/53904695/206603279-618a88d4-fbd2-4d70-af50-18185aaa9fbf.png)

Y en esta segunda imagen ,  despues de presionar el boton comprar el pedido da error . Despues de varios intentos de hacer un pedido exitoso ,llego conclusion que el campo "INDICACIONES" es un campo obligatorio, el cual deberian identificar como obligatorio.

Cualquier cosita pueden contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by eliseoe95** [comment]
Ya realizamos el campo indicaciones obligatorio.
