### ISSUE TITLE
Eliminar Comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [agustines82/ComiteandoRestaurant#43]
Buen@s!!  como va?  encontre algunos comentarios en el codigo.

![image](https://user-images.githubusercontent.com/53904695/206605090-0e4272dd-08ae-4a7a-9a1d-0c44181b6507.png)

Comentarios como estos hay varios en el codigo, recordemos que si bien los comentarios no alteran el funcionamiento del codigo, en  si no estan vistos como una buena practica.

Cualquier cosita pueden contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by eliseoe95** [comment]
Ya eliminamos todos los comentarios
